#ifndef MYDEVICESUPPORT_GLOBAL_H
#define MYDEVICESUPPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYDEVICESUPPORT_LIBRARY)
#define MYDEVICESUPPORT_EXPORT Q_DECL_EXPORT
#else
#define MYDEVICESUPPORT_EXPORT Q_DECL_IMPORT
#endif

#endif // MYDEVICESUPPORT_GLOBAL_H
